services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    volumes:
      - eshop-zipkin:/data/trace
    networks:
      - eshop
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - 8888:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password123456
    command:
      - start-dev
    volumes:
      - eshop-keycloak:/data/keycloak
    networks:
      - eshop
  mongodb:
    image: mongo:4.2.24
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - eshop-mongodb:/data/db
    networks:
      - eshop
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password123456
    ports:
      - 3306:3306
    volumes:
      - eshop-mysql:/var/lib/mysql
    networks:
      - eshop
volumes:
  eshop-zipkin:
  eshop-keycloak:
  eshop-mongodb:
  eshop-mysql:
networks:
  eshop:
